version: "2"

run:
  timeout: 10m
  tests: true
  build-tags:
    - !no_fyne
    - !no_systray

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    # Keep essential linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - unconvert
    - misspell
  disable:
    # Disable noisy linters for internal packages
    - revive     # Too many documentation requirements
    - unused     # Many functions planned for future use
    - gosec      # Security warnings too strict for development
    - gocritic   # Code style suggestions too aggressive
    - gocognit   # Cognitive complexity acceptable for GUI apps
    - gocyclo    # Cyclomatic complexity acceptable for UI code
    - goconst    # Constant extraction not always beneficial
    - unparam    # Unused parameter warnings too strict
    - nakedret   # Naked returns acceptable in some contexts
    - dogsled    # Blank identifier restrictions too strict
    - dupl       # Duplicate code acceptable for similar UI handlers
    - prealloc   # Memory allocation suggestions not critical
    - whitespace # Formatting handled by gofmt
    

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: meshgo

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    min-confidence: 0.8
  gosec:
    excludes:
      - G304  # File path provided as taint input (common in CLI apps)
      - G204  # Subprocess launched with function call as argument (common in CLI apps)
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 10
  dogsled:
    max-blank-identifiers: 2
  gocognit:
    min-complexity: 20

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude errcheck from test files for cleanup functions
    - path: _test\.go
      linters:
        - errcheck
    
    # Allow protobuf generated files to have all issues
    - path: ".*\\.pb\\.go"
      linters:
        - revive
        - staticcheck
        - unused
        - ineffassign
    
    # Allow specific errcheck exclusions for defer cleanup
    - text: "Error return value of.*RemoveAll.* is not checked"
      linters:
        - errcheck
    - text: "Error return value of.*Close.* is not checked"
      linters:
        - errcheck
    - text: "Error return value of.*Setenv.* is not checked"  
      linters:
        - errcheck
    - text: "Error return value of.*Unsetenv.* is not checked"
      linters:
        - errcheck