when:
  - event: [push, tag]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0

steps:
  fmt:
    image: golang:1.25-alpine
    commands:
      - |
        export PATH=/usr/local/go/bin:/go/bin:$PATH
        fmt_out=$(/usr/local/go/bin/gofmt -l ./cmd ./internal 2>/dev/null)
        if [ -n "$fmt_out" ]; then
          echo "The following files need gofmt:"
          echo "$fmt_out"
          exit 1
        fi

  lint:
    image: golang:1.25-alpine
    commands:
      - export PATH=/usr/local/go/bin:/go/bin:$PATH
      - export CACHE_ROOT="$PWD/.ci-cache"
      - export GOMODCACHE="$CACHE_ROOT/gomod"
      - export GOCACHE="$CACHE_ROOT/gobuild"
      - export GOPATH="$CACHE_ROOT/gopath"
      - export XDG_CACHE_HOME="$CACHE_ROOT/xdg"
      - mkdir -p "$GOMODCACHE" "$GOCACHE" "$GOPATH/bin" "$XDG_CACHE_HOME"
      - apk add --no-cache git build-base pkgconf mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.8.0
      - $GOPATH/bin/golangci-lint run

  vet:
    image: golang:1.25-alpine
    commands:
      - export PATH=/usr/local/go/bin:/go/bin:$PATH
      - export CACHE_ROOT="$PWD/.ci-cache"
      - export GOMODCACHE="$CACHE_ROOT/gomod"
      - export GOCACHE="$CACHE_ROOT/gobuild"
      - export GOPATH="$CACHE_ROOT/gopath"
      - mkdir -p "$GOMODCACHE" "$GOCACHE" "$GOPATH/bin"
      - apk add --no-cache build-base pkgconf mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - go vet ./...

  test:
    image: golang:1.25-alpine
    commands:
      - export PATH=/usr/local/go/bin:/go/bin:$PATH
      - export CACHE_ROOT="$PWD/.ci-cache"
      - export GOMODCACHE="$CACHE_ROOT/gomod"
      - export GOCACHE="$CACHE_ROOT/gobuild"
      - export GOPATH="$CACHE_ROOT/gopath"
      - mkdir -p "$GOMODCACHE" "$GOCACHE" "$GOPATH/bin"
      - apk add --no-cache build-base pkgconf mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - go test ./...

  build:
    image: golang:1.25-alpine
    commands:
      - export PATH=/usr/local/go/bin:/go/bin:$PATH
      - export CACHE_ROOT="$PWD/.ci-cache"
      - export GOMODCACHE="$CACHE_ROOT/gomod"
      - export GOCACHE="$CACHE_ROOT/gobuild"
      - export GOPATH="$CACHE_ROOT/gopath"
      - mkdir -p "$GOMODCACHE" "$GOCACHE" "$GOPATH/bin"
      - apk add --no-cache build-base pkgconf mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - mkdir -p dist
      - go build -trimpath -o dist/meshgo-debug ./cmd/debug
      - go build -trimpath -o dist/meshgo ./cmd/gui

  release:
    image: golang:1.25-alpine
    environment:
      GITEA_TOKEN:
        from_secret: GITEA_TOKEN
    commands:
      - export PATH=/usr/local/go/bin:/go/bin:$PATH
      - export CACHE_ROOT="$PWD/.ci-cache"
      - export GOMODCACHE="$CACHE_ROOT/gomod"
      - export GOCACHE="$CACHE_ROOT/gobuild"
      - export GOPATH="$CACHE_ROOT/gopath"
      - mkdir -p "$GOMODCACHE" "$GOCACHE" "$GOPATH/bin"
      - test -n "$CI_FORGE_URL" || (echo "CI_FORGE_URL is empty. Cannot derive Forge URLs for GoReleaser." && exit 1)
      - test -n "$FORGE_API_URL" || export FORGE_API_URL="$CI_FORGE_URL/api/v1"
      - test -n "$FORGE_DOWNLOAD_URL" || export FORGE_DOWNLOAD_URL="$CI_FORGE_URL"
      - apk add --no-cache git build-base pkgconf mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mingw-w64-gcc
      - go install github.com/goreleaser/goreleaser/v2@v2.12.7
      - $GOPATH/bin/goreleaser release --clean
    when:
      - event: tag
